language: go

go:
  - "1.11"

services:
  - docker

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - wget https://github.com/Crazybus/lope/releases/download/0.4.0/lope-linux_amd64 -O lope && chmod +x lope
  - ./lope golang:1.15 '/usr/local/go/bin/go run build/build.go'

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: WbLVKDAjp+vvxqJXbi8psvoZY6y/0ipj3hLOTNK2l/bDjFLajT1XaMoFP5gAbG3yH2AMHkIHrfhlnHvv+mhKyryLokhGJ7MyAYLriziNNjWsC0Wi2ImyPYcD/lPNLi3izH9WLLSUIWV1WTBuMqE8X5rH/TfmMXAJ8kQ7gJRJOFkDmaEuhLIDKbB/g1+gOxxnNlIwnxhiytXRdC6pGMJl62tkqBC6CqVWvqxGW37zOn8eiIY7y7f/tAAbE4gtwTZKWdcob7THqY+RTOu5Z4AyvCTOItgI3meJiCumHGQzjZgQvgiYqE/QhQTzfuQvc5nDKNSF0ybdaPLrccE2fMaOGnh179dC9JhJJVSi57dvgEu+OIOK96f9D0lSj8BMIV7nUoYrePLEaMg5QYkrdxVPoMfVxXtgcZ/swdkMVNEJ+W9imJvWA5FEcGaY3gvcgsT682WHEEdnKbmQGVMhZGJTNQka0zJVyriKABBgxCz2p+mOq8Pka/hWgDHpRBm9hCXf7AhVJXh/SPrKobhUvoKkVAF+QnRljn7gVNUeCPSppMbiSdqoLWlWhr09VYzk1Zmcl4rd/2cyAM6k124x3Zt6PqZjBMLm1cXSKN6ZEYAMjMA5AXROAgwbcK6ohppk7uHJoyxeqzxjg1WktyIzRwJ1If/bA+3BXx85W9gyu2czMgY=
  file_glob: true
  file: build/pratus*
  skip_cleanup: true
  on:
    tags: true
